name: Deploy Docker
on: [push]
jobs:
  deploy:
    name: Deploy to Docker
    uses: wshihadeh/docker-deployment-action@v1
    with:
      remote_docker_host: root@cloud.grey.software
      ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
      ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
      deployment_mode: docker-compose
      args: up -d
      pull_images_first: 'true'